### ISSUE TITLE
Why not use setImmediate to speed up things?

### ISSUE THREAD

**Issue by ghost** [rollup/rollup-watch#14]
Why not use  `setImmediate` to speed up things?  `setImmediate` is faster then `process.nextTick`, and can be done like this for compability reasons with older browser:

``` js
const nextTick = typeof setImmediate !== 'undefined'
    ? setImmediate
    : process.nextTick;
```

**Comment by TrySound** [comment]
@Kflash Watcher in browser? Is there any case for this?

**Comment by ghost** [comment]
https://nodejs.org/api/timers.html

**Comment by ghost** [comment]
`timers.setImmediate` is the correct usage. It's used by some other popular
libraries and framework to speed things up server side with NodeJS.

**Comment by bruce-one** [comment]
I don't believe that `setImmediate` is faster than `process.nextTick` in Node :-s

According to the doc, `process.nextTick` doesn't process any additional I/O before continuing, whilst `setImmediate` does (implying that `process.nextTick` would be faster), and a quick dodgy benchmark seems to agree:

```
var i = 0

function increment() {
    if(i++ > 1e7) {
        console.log(i)
        process.exit(0)
    } else {
        _func_(increment)
    }
}

_func_(increment)
```

The `process.nextTick` version takes ~1 second, whilst the `setImmediate` one takes about 15 seconds. (Not executed particularly scientifically...)

I'd think it might be worth closing this issue? :-s (There's not a lot of activity/context either)

(Feel free to ignore me :-) the issue just caught my eye)

**Comment by Rich-Harris** [comment]
Going to close this as the current use of `setTimeout` is deliberate – it's quite common for multiple files to change at *almost* the same time (e.g. if you `git checkout` a different branch), and if you don't use a debouncing mechanism like `setTimeout` then you can easily end up triggering multiple builds where one will do. Thanks anyway!
