### ISSUE TITLE
Error catching

### ISSUE THREAD

**Issue by zwhitchcox** [rollup/rollup-watch#19]
Just curious as to why we are emitting errors as an event as opposed to returning a promise or logging them? Just spend about 2 hours trying to find an error without realizing it was going to emit an error event...

**Comment by zwhitchcox** [comment]
I would propose returning the rollup promise...I would also propose allowing people to pass in the rollup function, because most people import it like this:

```
import {rollup} from rollup
```

Maybe detect if rollup is a function, and if so use it as a function...I don't see anywhere in the code where we need the actual reference to the object, so, if so, that would be nice.

**Comment by zwhitchcox** [comment]
Also,

```
import rollup from 'rollup'
```

returns an error, so I don't even know how you're getting the rollup object

**Comment by TrySound** [comment]
@zwhitchcox To import rollup use 

```
import * as rollup from 'rollup';
```

We won't improve api with such conditions. API should be clean and simple. But I think would be better to pass rollup function instead.

/cc @Rich-Harris 

About promises. You can resolve it just once. But watcher is iterated again and again. So your propose is not the case.
Logging works when you use CLI. In this case it's the same as logging promise rejection.

**Comment by zwhitchcox** [comment]
So, we have to use the CLI or listen for the error even if we want to get the errors?

You're saying the promise is only going to catch the error once, but writing

```
.then(()=> {}, error => console.log(error))
```

is the same as writing 

```
.then(()=>{})
.catch(err => console.log(err))
```

Correct?

Or am I missing something here?

**Comment by TrySound** [comment]
Yep, it's the same. And both will be called once. With event emitter you may call listeners any times.

**Comment by TrySound** [comment]
Different API for different purposes.

**Comment by zwhitchcox** [comment]
gotcha...modified my [pr](https://github.com/rollup/rollup-watch/pull/20/files)...how's that?

will detect if run by command line, and if not, will output error....

rollup already shows the error twice for me, don't want a third time XD

**Comment by TrySound** [comment]
@zwhitchcox It's already done in CLI
https://github.com/rollup/rollup/blob/master/bin/src/runRollup.js#L162-L194

**Comment by zwhitchcox** [comment]
Oh ok...well, for me, it doesn't log an error

**Comment by zwhitchcox** [comment]
if I don't use watch, it does log an error...if I do use watch, then it doesn't log an error

**Comment by zwhitchcox** [comment]
Yes, but it doesn't log the error with the programmatic api, right?

**Comment by zwhitchcox** [comment]
Yes, but it doesn't log the error with the programmatic api, right?

**Comment by zwhitchcox** [comment]
Yes, but it doesn't log the error withthe programmatic api, e.g.:

``` js
  1 // I roll up, I roll up, I roll up, Shawty I roll up                                                                                    
  2 import * as rollup from 'rollup'                                                                                                        
  3 import watch from 'rollup-watch'                                                                                                        
  4 import config from '../rollup.config.js'                                                                                                
  5 watch(rollup, config)                                                                                                                   
  6   .on('event', e => e.code === 'ERROR' && console.log(e))    
```

unless you listen for the event...or is this the intended behavior...also, +1 for this not being the intended behavior haha

**Comment by talmobi** [comment]
In my small watcher wrapper I directly use rollups js API (without rollup-watch) and catch the errors from the rollup.rollup promise directly. Seems to work pretty OK since a rebuild is done on each change (using cache if available of course).

(and onwarns that pass `if ( /Treating .+ as external dependency/.test( message ) ) return`

2cents

**Comment by zwhitchcox** [comment]
Thank you!

Yeah, I actually did get rollup-watch to work, but now there's other problems with rollup that I can't figure out :|...So, I think I'm just gonna make my life a whole lot easier and use jspm, because I'm not developing a library XD
