### ISSUE TITLE
Errors are swallowed in promises

### ISSUE THREAD

**Issue by TrySound** [rollup/rollup-watch#2]
Ref https://github.com/rollup/rollup/issues/712

Errors should be catched here
https://github.com/rollup/rollup-watch/blob/master/src/index.js#L83
By the way. Don't have an access to this repo.

**Comment by Rich-Harris** [comment]
Have added @rollup/collaborators to this repo (wish GitHub did that automatically for repos in the org), and released 2.2.0 with a fix for this. Now just need to handle the errors in Rollup itself

**Comment by TrySound** [comment]
I think that caz I don't have admin access.

**Comment by Rich-Harris** [comment]
am totally flummoxed by GitHub's UI for teams, but I _think_ I've just fixed that
