### ISSUE TITLE
Remove version check

### ISSUE THREAD

**Issue by PaulBGD** [rollup/rollup-watch#26]
Earlier today Dyn went down and so did GitHub/NPM. Since my workflow is entirely offline, I could still work except for one thing: rollup-watch stalls on checking for version because it depends on NPM being online. I don't think that a version check should be required every run, especially since rollup-watch doesn't update very often.

**Comment by talmobi** [comment]
Without trying to blow my own horn but I've had similar experiences with rollup-watch and therefore made my own tiny watch wrapper https://github.com/talmobi/wrollup (mostly copy pasted from rollup-watch) to fix some of these inconsistencies.

It requires a rollup.config.js file so instead of

`rollup -w -c rollup.config.js`

use

`wrollup -c rollup.config.js`

2cents

**Comment by PaulBGD** [comment]
@talmobi I saw that in another thread and thought it looked cool. Definitely wanted to open this issue though so that the maintainers saw that this is a requested feature.

**Comment by anttikissa** [comment]
[Issue 12](https://github.com/rollup/rollup-watch/issues/12) seems to be about the same thing.

For a quick & dirty fix (if you're comfortable with editing stuff inside `node_modules`), you can disable the version check by adding a `Promise.resolve()` in `node_modules/rollup-watch/dist/rollup-watch.cjs.js`:

```
function checkVersion ( name, localVersion ) {
    // Hack to bypass version check
    return Promise.resolve();

    return new Promise( function ( fulfil, reject ) {
```

**Comment by PaulBGD** [comment]
Oh haha @talmobi you could've mentioned you already had an issue open for this.

**Comment by talmobi** [comment]
The more the merrier! 🎅

**Comment by chiel** [comment]
I was having the same issue while on a plane this week. I don't quite understand why the version check is required in the first place.

**Comment by aliafshar** [comment]
Should default to not check for new versions imho. I code 100% offline, for example and this is very annoying and slows things down a lot.

**Comment by Rich-Harris** [comment]
Agree, the check is unnecessary. It was useful for me personally at first, when the design was in flux and I was trying it out on more than one machine, but it was always predicated on the idea that rollup-watch would typically be globally installed, which doesn't really work in practice. Will cut a new release shortly
