### ISSUE TITLE
I wrote the `.rollup()` function in a pack.js  and run `node pack.js` in the command line to pack. In other words, I take the way not running `rollup xxx.config.js` in the command line. My question is how to use -c --watch in this situation?

### ISSUE THREAD

**Issue by mobilesite** [rollup/rollup-watch#29]
I wrote the `.rollup()` function in a pack.js  and run `node pack.js` in the command line to pack. In other words, I take the way not running `rollup xxx.config.js` in the command line. My question is how to use -c --watch in this situation?

**Comment by Rich-Harris** [comment]
Short answer is you can't – rollup-watch is designed for use with the CLI. But you can use it via the JavaScript API (the way the CLI itself does):

```js
const rollup = require( 'rollup' );
const watch = require( 'watch' );

const watcher = watch( rollup, {
  entry: 'src/index.js',
  // ...other options...
});

// the watcher will tick away indefinitely (there isn't currently
// a way to turn it off)

watcher.on( 'event', event => {
  // event.code is one of BUILD_START, BUILD_END, ERROR
});
```
