### ISSUE TITLE
Duplicate watchers on same file when linking.

### ISSUE THREAD

**Issue by youzi** [rollup/rollup-watch#32]
When we have:

**files:**
dep-b
project-a/node_modules/dep-b --> links to b
project-a/node_modules/c/node_modules/dep-b  --> links to b

rollup-watch adds creates 2 FileWatchers for dep-b

**Comment by Rich-Harris** [comment]
Presumably the answer to this would be to use `fs.realpath`

**Comment by Rich-Harris** [comment]
Fixed in 3.1.0
