### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by youzi** [rollup/rollup-watch#36]
Since:
https://github.com/rollup/rollup-watch/commit/bed4201d2f41b8fdce6017b265c6f3c421ec320b
rollup-watch crashes when not defining `opts.dest`

```js
const dests = options.dest ? [ path.resolve( options.dest ) ] : options.target.map( target => path.resolve( target.dest ) );
```
Should probably be mapping `opts.target**s**` (notice the "s"):
```js
const dests = options.dest ? [ path.resolve( options.dest ) ] : options.targets.map( target => path.resolve( target.dest ) );
```

Unless the API changed from using `.targets` towards using `.target` ofc

**Comment by Rich-Harris** [comment]
Released 3.2.0 with the fix — thanks
