### ISSUE TITLE
chokidar is never used

### ISSUE THREAD

**Issue by AdamHerrmann** [rollup/rollup-watch#45]
As built, `chokidar` will never be used because `requireRelative` always throws an error.  The generated commonjs  code looks like this:

```javascript
var path = require('path');
var path__default = path['default'];

var path$1 = path__default;

var getModule = function(dir) {
  var rootPath = dir ? path$1.resolve(dir) : process.cwd(); // <-- This line throws b/c
                                                            // require('path')['default'].resolve
                                                            // isn't a function
  // ...
};
```

I think this is likely an issue with `rollup-plugin-commonjs`.  Once I've convinced myself that's true, I'll file an issue there.  Here is a [small reproducer](http://rollupjs.org/?version=0.41.4&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwKiUyMGFzJTIwcGF0aCUyMGZyb20lMjAncGF0aCclM0IlNUNuaW1wb3J0JTIwcmVxdWlyZVJlbGF0aXZlJTIwZnJvbSUyMCcuJTJGcmVxdWlyZS1yZWxhdGl2ZS5qcyclNUNuJTVDbnJlcXVpcmVSZWxhdGl2ZShwYXRoLnJlc29sdmUoJy4nKSklM0IlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnJlcXVpcmUtcmVsYXRpdmUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwcGF0aCUyMGZyb20lMjAnLiUyRmNvbW1vbmpzLWV4dGVybmFsJTNBcGF0aCclNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjBmdW5jdGlvbiUyMChwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIwcGF0aC5yZXNvbHZlKHApJTNCJTVDbiU3RCU1Q24lMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY29tbW9uanMtZXh0ZXJuYWwlM0FwYXRoJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHBhdGglMjBmcm9tJTIwJ3BhdGgnJTNCJTIwZXhwb3J0JTIwZGVmYXVsdCUyMHBhdGglM0IlNUNuJTIyJTdEJTVEJTdE) that I think demonstrates the issue

**Comment by AdamHerrmann** [comment]
Based on [this comment](https://github.com/rollup/rollup/issues/1267#issuecomment-272917970) maybe the answer is to change 

```javascript
import * as path from 'path';
```

to 

```javascript
import path from 'path';
```

and let `_interopDefault` handle it?

**Comment by DaveWM** [comment]
@AdamHerrmann I've created a PR (#49) with your suggested fix, seems to work :)

**Comment by Rich-Harris** [comment]
This is now fixed thanks to @DaveWM
