### ISSUE TITLE
check if in watch mode in rollup.config.js

### ISSUE THREAD

**Issue by gerwinbrunner** [rollup/rollup-watch#48]
Is there a way to figure out if the rollup was started with the --watch flag?

I'm trying to figure out in rollup.config.js if the watch flag is set to skip the liverelode and serve plugin.

**Comment by Rich-Harris** [comment]
Agree — I'm planning to add a `process.env.ROLLUP_WATCH` environment variable, which would be `"true"` or `undefined`. That sound like a sensible solution? Related issue: https://github.com/rollup/rollup/issues/1429

**Comment by meszaros-lajos-gyorgy** [comment]
A temporary solution, which works for me is to have this line of code in my rollup.config.js:

```javascript
const isWatching = process.argv.includes('-w') || process.argv.includes('--watch')
```

**Comment by Rich-Harris** [comment]
This was recently added to Rollup itself, so I'll close this. My rollup.config.js files often look like this now:

```js
import uglify from 'rollup-plugin-uglify';

// dev build if watching, prod build if not
const production = !process.env.ROLLUP_WATCH;

export default {
  entry: 'src/main.js',
  dest: 'public/bundle.js',
  format: 'iife',
  plugins: [
    prod && uglify()
  ]
};
```

**Comment by meszaros-lajos-gyorgy** [comment]
Can you please add a note on this in the documentation?

**Comment by rmx90210** [comment]
+1 for adding this to the docs :)
