### ISSUE TITLE
Slow builds

### ISSUE THREAD

**Issue by PaulBGD** [rollup/rollup-watch#5]
First off, congrats on the release. This is a much awaited feature.

The build times however are not too great. I'm bundling react and a couple of internal files and my build times look like:

2715ms > 2065ms > 2052ms > ...

700ms is definitely an improvement, but not by much. What needs to be done to improve the rebuild speed?

**Comment by TrySound** [comment]
Now rollup caches and reuses transformations result, but it still parses and shakes modules each time.

**Comment by TrySound** [comment]
@Rich-Harris Some time ago disabling tree shaking was introduced. Maybe with that option we can cache a bit more and prevent reparsing for it? In this case we could enable tree shaking only for prod.

**Comment by Rich-Harris** [comment]
Hey – I've moved this issue over to https://github.com/rollup/rollup/issues/723, as rollup-watch is just a small wrapper that sits between Rollup and the filesystem.
