### ISSUE TITLE
Can't find module on rebuild

### ISSUE THREAD

**Issue by chiel** [rollup/rollup-watch#54]
I have a weird issue where the initial build goes perfectly fine, but on rebuilds I get
```
🚨   Could not load crypto (imported by /Users/chiel/dev/fitmate/node_modules/cookie-signature/index.js): ENOENT: no such file or directory, open 'crypto'
```

This, however, only seems to happen for serverside builds, as I've never had the issue building client bundles.

I've made a small repro repo here: https://github.com/chielkunkels/rollup-watch-issue

After you clone it you can run
```
yarn
yarn watch
```
And then change something in the `src/server/index.js`. It fails for me with the error:
```
🚨   Could not load events (imported by /Users/chiel/dev/rollup-issue/node_modules/express/lib/express.js): ENOENT: no such file or directory, open 'events'
```
Thanks for the rollup, it's awesome.

Let me know if there's anything I can do to help!

**Comment by chiel** [comment]
It occured to me on the bike to work this morning that this only seems to happen for built-ins -
 `crypto` and `events` in the above examples.

As such, I decided to distil the repro repo into a more minimal reproducable case. While doing so I discovered that it only happens if you're editing another file than where the import is happening.

So when cloning the above repo, if you install it and then change something in `src/server/index.js`, things will break. If you change something in `src/server/someHelper.js`, everything will actually be fine.

Hope this helps!

**Comment by Rich-Harris** [comment]
Turns out this was the fault of Rollup itself — it was storing info about how IDs were resolved relative to each module in a way that meant subsequent builds were given incorrect information. Should be fixed as of 0.45.2. Thanks!

**Comment by chiel** [comment]
Ah cool, I was not sure whether it was something watch-specific or rollup itself. Thanks so much for the fix!

**Comment by scottmas** [comment]
This is happening to me also. First build is fine. Rebuilds blow up with a `no such file or directory` error. 

This is likely occurring since I have multiple `node_modules` - one at root and then one in a subdirectory. 

I have a pretty generic rollup file, as you can see:

```javascript
import babel from "rollup-plugin-babel";
import babelrc from "babelrc-rollup";

export default {
  input: "./functions/index.js",
  output: {
    file: "./functions/bundle.js",
    format: "cjs",
    strict: false
  },
  plugins: [
    babel(babelrc({ path: ".babelrc-functions" }))
  ]
};
```

As a workaround, I'm using the [onchange](https://www.npmjs.com/package/onchange) package to restart the entire script

**Comment by Dakkers** [comment]
happening to me as well, but I don't have another `node_modules` dir (though I am using a link...)

**Comment by RichieAHB** [comment]
This is happening to me and I'm also `yarn link`ing my rollup app over to another module.

**Comment by louiejakebell** [comment]
i am also experiencing a similar problem whilst using yarn workspaces (similar to yarn link) for managing libraries. common dependencies are hoisted into the parent node_modules folder which could explain why particular dependencies are not found whilst running `rollup watch`?

**Comment by lazarljubenovic** [comment]
I'm getting this for `crypto` as described by the OP. Apparently the mentioned PR didn't fix this.

**Comment by kevinfiol** [comment]
Also getting this issue. Very puzzled as to what's causing it.

**Comment by louiejakebell** [comment]
to prevent these warnings you need to explicitly define all dependencies which should be treated as external dependencies so that they won't be included inside the rollup bundle. this is achieved by using **external** inside the rollup.config.js and passing it an array


```
// rollup.config.js
export default {
  ... 
  external: ['crypto']
  ...
}
```

**Comment by kevinfiol** [comment]
> 
> 
> to prevent these warnings you need to explicitly define all dependencies which should be treated as external dependencies so that they won't be included inside the rollup bundle. this is achieved by using **external** inside the rollup.config.js and passing it an array
> 
> ```
> // rollup.config.js
> export default {
>   ... 
>   external: ['crypto']
>   ...
> }
> ```

Tried this, but still receive the warning, and still errors out in the browser.
