### ISSUE TITLE
Providing a more reusable/callable API

### ISSUE THREAD

**Issue by marijnh** [rollup/rollup-watch#59]
My problem: I want to set up a single process that watches and rolls up a bunch of separate modules (the various parts of the ProseMirror library). (If there's a way to do that from the rollup binary, let me know, but my conclusion was that there isn't.)

It more or less works if I call the function exported by this module a bunch of times with a bunch of different config objects, but I get...

```
Warning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
Warning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
Warning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
Warning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
```
... because starting a watch process and registering those signal handlers happens through the same call.

Would a PR that adds an option to suppress adding signal handlers be welcome? Any problem I'll run into when running the watcher without those handlers?

**Comment by tivac** [comment]
You can export an array of configs from `rollup.config.js`,  rollup natively supports it and it works correctly with rollup-watch in my experiments.

**Comment by tivac** [comment]
Wrote up some quick docs on that since this keeps coming up.

https://github.com/rollup/rollup/wiki/Command-Line-Interface#multiple-configs

**Comment by marijnh** [comment]
Thanks! That's very useful. However, the same warnings pop up when I run rollup with `-w` on a config file that exports an array, so I guess that suggests factoring out the auto-closing logic to be something that the caller has to take care of, and moving the event handler registration into the `rollup` binary.

**Comment by marijnh** [comment]
(I'll do it and submit PRs, if breaking changes to `rollup-watch` are okay.)

**Comment by Rich-Harris** [comment]
I'm planning to merge `rollup-watch` into Rollup core, because having them in separate projects has proven an unnecessary source of pain and complexity. Will probably happen as part of https://github.com/rollup/rollup/pull/1491, since it's very difficult to batch stuff at the moment because there's no external control over the order in which things happen.

So it's probably best to hold off on that PR if you can bear with me... 😬 Just to be clear, is the issue that you're watching more than *n* configs (where n=11, I assume)? Or is this a leak of some kind?

**Comment by marijnh** [comment]
Thanks! I'll just bump max-listeners for now to suppress the noise.
