### ISSUE TITLE
confused about rollup watch

### ISSUE THREAD

**Issue by ghost** [rollup/rollup-watch#6]
Hey bro! Can you let me know how to setup identical code as this with Rollup watch?? https://github.com/jmeas/bizniz.js/blob/d52943fe29da148963a10f6bc803ac7ca8571208/gulpfile.babel.js#L158-L218

Yeah, I'm fucked up atm. Spent too many hours. Can't get livereload working. Any ideas bro? Would be nice to have it working outside Gulp!! 

Love yeah all! Cheers!

**Comment by TrySound** [comment]
@jonnyOwnTheWorld rollup-watch is the only CLI util. It uses chokidar as watcher. To make build faster you can cache `bundle` in external variable and pass it in the next time as `cache` option.
