### ISSUE TITLE
[bug] Rebuilds twice, then stops rebuilding.

### ISSUE THREAD

**Issue by trusktr** [rollup/rollup-watch#61]
After the second rebuild, modifying the same file stops triggering a rebuild.

Version: 4.3.1

Possibly related: https://github.com/rollup/rollup-watch/issues/51

**Comment by talmobi** [comment]
`rollup` now comes with its own --watch flag and this repo ( and plugin ) has been deprecated. There's a similar issue posted on the main `rollup` repo already FYI: https://github.com/rollup/rollup/issues/1666

**Comment by trusktr** [comment]
Ah, looks nice. I'll close this, and reopen on rollup if it happens with rollup.

**Comment by trusktr** [comment]
[Happening with Rollup too](https://github.com/rollup/rollup/issues/1669).
