### ISSUE TITLE
Doesn't re-use bundle for caching

### ISSUE THREAD

**Issue by tivac** [rollup/rollup-watch#8]
It looks like rollup supports setting the `cache` property on the options to a previously-generated bundle to speed up builds in [Bundle.js#L24-L28](https://github.com/rollup/rollup/blob/78db6134afd2e371e75d06abe846e51064ef61f6/src/Bundle.js#L24-L28), which is awesome.

Unfortunately `rollup-watch` doesn't seem to use this feature to speed up watched builds. Any particular reason? Could it? I'd happily send a PR if it would help! I just switched from `browserify` + `rollupify` over to `rollup-watch` and the lack of incremental builds is pretty brutal.

**Comment by Rich-Harris** [comment]
Huh – I could have _sworn_...

That PR would be great, thanks! Note that even with incremental rebuilds, there's a bit of work we still need to do before it's as fast as it can be: https://github.com/rollup/rollup/issues/723

**Comment by tivac** [comment]
Cool, working on it atm.

**Comment by Rich-Harris** [comment]
Thanks! Released 2.5.0
